language: python
dist: xenial

branches:
  only:
  - master

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - MPLBACKEND=Agg

matrix:

    include:

        # Check for sphinx doc build warnings
        # - os: linux
        #   env: CMD='sphinx-build'

        # macOS
        - os: osx
          python: 3.6
          env: TOXENV=py36
        - os: osx
          python: 2.7
          env: TOXENV=2.7

        # Linux
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
        - python: 2.7
          env: TOXENV=py27

        - python: 2.7
          env: TOXENV=flake8
        - python: 3.7
          env: TOXENV=flake8
        - python: 3.7
          env: TOXENV=black

        # Run regression tests
        # - os: linux
        #   env: PYTEST_OPTIONS='-v --ignore=tests'

install:
    - pip install tox

script:
    - tox
